<tr><th width="11.1%">Requested</th><th width="7.4%">CNN ID</th><th width="18.51%">Slug</th><th width="26.85%">Source &#x2192; Destination</th><th width="20.37%">Status</th><th width="7.4%">Duration</th><th width="8.33%">User</th></tr><tr><td>03:21:34</td><td><a href="http://bpstools/mediasource_admin/audit.html?selected_mediasource=production____atlanta____mediasource____production_atlanta_mediasource&cnnid=10974207" target="_blank">10974207</td><td>Bernanrd Young Clip</td><td>DC Omneon &#x2192; ATL Omneon</td><td class="completed"><img src="img/check.png" />COMPLETED</td><td>00:00:51</td><td>jargumedo</td></tr>
<tr><td>03:17:16</td><td><a href="http://bpstools/mediasource_admin/audit.html?selected_mediasource=production____atlanta____mediasource____production_atlanta_mediasource&cnnid=10944278" target="_blank">10944278</td><td>Rouhani Speech 4/09</td><td>NY Omneon &#x2192; NY Playback A</td><td class="completed"><img src="img/check.png" />COMPLETED</td><td>00:01:30</td><td>cscretchings</td></tr>
<tr><td>03:17:00</td><td><a href="http://bpstools/mediasource_admin/audit.html?selected_mediasource=production____atlanta____mediasource____production_atlanta_mediasource&cnnid=10973751" target="_blank">10973751</td><td>IRAN ARMED FORCES COS</td><td>NY Omneon &#x2192; NY Playback A</td><td class="completed"><img src="img/check.png" />COMPLETED</td><td>00:00:54</td><td>cscretchings</td></tr>
<tr><td>03:16:55</td><td><a href="http://bpstools/mediasource_admin/audit.html?selected_mediasource=production____atlanta____mediasource____production_atlanta_mediasource&cnnid=10973751" target="_blank">10973751</td><td>IRAN ARMED FORCES COS</td><td>ATL Omneon &#x2192; NY Omneon</td><td class="completed"><img src="img/check.png" />COMPLETED</td><td>00:00:54</td><td>cscretchings</td></tr>
<tr><td>03:14:29</td><td><a href="http://bpstools/mediasource_admin/audit.html?selected_mediasource=production____atlanta____mediasource____production_atlanta_mediasource&cnnid=10973750" target="_blank">10973750</td><td>Cats Rescued</td><td>ATL Omneon &#x2192; ATL Newsource</td><td class="completed"><img src="img/check.png" />COMPLETED</td><td>00:01:27</td><td>gmorrison</td></tr>
<tr><td>03:13:08</td><td><a href="http://bpstools/mediasource_admin/audit.html?selected_mediasource=production____atlanta____mediasource____production_atlanta_mediasource&cnnid=10973517" target="_blank">10973517</td><td>Xi Jinping arrive PAK</td><td>ATL Omneon &#x2192; ATL Newsource</td><td class="completed"><img src="img/check.png" />COMPLETED</td><td>00:01:04</td><td>paynea</td></tr>
<tr><td>03:12:36</td><td><a href="http://bpstools/mediasource_admin/audit.html?selected_mediasource=production____atlanta____mediasource____production_atlanta_mediasource&cnnid=10775092" target="_blank">10775092</td><td>BOBBI HOSPITAL AERIALS</td><td>ATL Omneon &#x2192; ATL Playback A</td><td class="completed"><img src="img/check.png" />COMPLETED</td><td>00:00:45</td><td>lihernandez</td></tr>
<tr><td>03:12:35</td><td><a href="http://bpstools/mediasource_admin/audit.html?selected_mediasource=production____atlanta____mediasource____production_atlanta_mediasource&cnnid=10775092" target="_blank">10775092</td><td>BOBBI HOSPITAL AERIALS</td><td>ATL Omneon &#x2192; ATL Playback B</td><td class="completed"><img src="img/check.png" />COMPLETED</td><td>00:00:45</td><td>lihernandez</td></tr>
<tr><td>03:11:38</td><td><a href="http://bpstools/mediasource_admin/audit.html?selected_mediasource=production____atlanta____mediasource____production_atlanta_mediasource&cnnid=10973747" target="_blank">10973747</td><td>SK Businessman's suicid</td><td>ATL Omneon &#x2192; ATL Playback A</td><td class="completed"><img src="img/check.png" />COMPLETED</td><td>00:00:51</td><td>wilkinsons</td></tr>
<tr><td>03:11:38</td><td><a href="http://bpstools/mediasource_admin/audit.html?selected_mediasource=production____atlanta____mediasource____production_atlanta_mediasource&cnnid=10973747" target="_blank">10973747</td><td>SK Businessman's suicid</td><td>ATL Omneon &#x2192; ATL Playback B</td><td class="completed"><img src="img/check.png" />COMPLETED</td><td>00:00:51</td><td>wilkinsons</td></tr>
<tr><td>03:11:06</td><td><a href="http://bpstools/mediasource_admin/audit.html?selected_mediasource=production____atlanta____mediasource____production_atlanta_mediasource&cnnid=10869725" target="_blank">10869725</td><td>IRAQ MOVING ON TIKRIT</td><td>NY Omneon &#x2192; NY Playback A</td><td class="completed"><img src="img/check.png" />COMPLETED</td><td>00:00:47</td><td>cscretchings</td></tr>
<tr><td>03:11:03</td><td><a href="http://bpstools/mediasource_admin/audit.html?selected_mediasource=production____atlanta____mediasource____production_atlanta_mediasource&cnnid=10869725" target="_blank">10869725</td><td>IRAQ MOVING ON TIKRIT</td><td>ATL Omneon &#x2192; NY Omneon</td><td class="completed"><img src="img/check.png" />COMPLETED</td><td>00:00:47</td><td>cscretchings</td></tr>
<tr><td>03:10:20</td><td><a href="http://bpstools/mediasource_admin/audit.html?selected_mediasource=production____atlanta____mediasource____production_atlanta_mediasource&cnnid=undefined" target="_blank">undefined</td><td>undefined</td><td>NY Omneon &#x2192; NY Playback A</td><td class="completed"><img src="img/check.png" />COMPLETED</td><td>N/A</td><td>cscretchings</td></tr>
<tr><td>03:10:18</td><td><a href="http://bpstools/mediasource_admin/audit.html?selected_mediasource=production____atlanta____mediasource____production_atlanta_mediasource&cnnid=10803415" target="_blank">10803415</td><td>Iraq KURDS FIREFIGHT</td><td>ATL Omneon &#x2192; NY Omneon</td><td class="completed"><img src="img/check.png" />COMPLETED</td><td>00:00:45</td><td>cscretchings</td></tr>
<tr><td>03:09:32</td><td><a href="http://bpstools/mediasource_admin/audit.html?selected_mediasource=production____atlanta____mediasource____production_atlanta_mediasource&cnnid=10973523" target="_blank">10973523</td><td>Empty Shelves</td><td>NY Omneon &#x2192; NY Playback A</td><td class="completed"><img src="img/check.png" />COMPLETED</td><td>00:00:56</td><td>scohen</td></tr>
<tr><td>03:09:28</td><td><a href="http://bpstools/mediasource_admin/audit.html?selected_mediasource=production____atlanta____mediasource____production_atlanta_mediasource&cnnid=10973523" target="_blank">10973523</td><td>Empty Shelves</td><td>ATL Omneon &#x2192; NY Omneon</td><td class="completed"><img src="img/check.png" />COMPLETED</td><td>00:00:56</td><td>scohen</td></tr>
<tr><td>03:07:06</td><td><a href="http://bpstools/mediasource_admin/audit.html?selected_mediasource=production____atlanta____mediasource____production_atlanta_mediasource&cnnid=10973648" target="_blank">10973648</td><td>BOBBY BROWN CONCERT</td><td>ATL Omneon &#x2192; ATL Playback A</td><td class="completed"><img src="img/check.png" />COMPLETED</td><td>00:00:57</td><td>cibikc</td></tr>
<tr><td>03:07:05</td><td><a href="http://bpstools/mediasource_admin/audit.html?selected_mediasource=production____atlanta____mediasource____production_atlanta_mediasource&cnnid=10973648" target="_blank">10973648</td><td>BOBBY BROWN CONCERT</td><td>ATL Omneon &#x2192; ATL Playback B</td><td class="completed"><img src="img/check.png" />COMPLETED</td><td>00:00:57</td><td>cibikc</td></tr>
<tr><td>03:07:05</td><td><a href="http://bpstools/mediasource_admin/audit.html?selected_mediasource=production____atlanta____mediasource____production_atlanta_mediasource&cnnid=10973648" target="_blank">10973648</td><td>BOBBY BROWN CONCERT</td><td>NY Omneon &#x2192; NY Playback A</td><td class="completed"><img src="img/check.png" />COMPLETED</td><td>00:00:57</td><td>cibikc</td></tr>
<tr><td>03:07:01</td><td><a href="http://bpstools/mediasource_admin/audit.html?selected_mediasource=production____atlanta____mediasource____production_atlanta_mediasource&cnnid=10973648" target="_blank">10973648</td><td>BOBBY BROWN CONCERT</td><td>ATL Omneon &#x2192; NY Omneon</td><td class="completed"><img src="img/check.png" />COMPLETED</td><td>00:00:57</td><td>cibikc</td></tr>
<tr><td>03:06:41</td><td><a href="http://bpstools/mediasource_admin/audit.html?selected_mediasource=production____atlanta____mediasource____production_atlanta_mediasource&cnnid=10973744" target="_blank">10973744</td><td>Clinton Distraction BTS</td><td>NY Omneon &#x2192; NY Playback A</td><td class="completed"><img src="img/check.png" />COMPLETED</td><td>00:00:21</td><td>coverstreet</td></tr>
<tr><td>03:06:35</td><td><a href="http://bpstools/mediasource_admin/audit.html?selected_mediasource=production____atlanta____mediasource____production_atlanta_mediasource&cnnid=10973744" target="_blank">10973744</td><td>Clinton Distraction BTS</td><td>ATL Omneon &#x2192; NY Omneon</td><td class="completed"><img src="img/check.png" />COMPLETED</td><td>00:00:21</td><td>coverstreet</td></tr>
<tr><td>03:04:28</td><td><a href="http://bpstools/mediasource_admin/audit.html?selected_mediasource=production____atlanta____mediasource____production_atlanta_mediasource&cnnid=10972276" target="_blank">10972276</td><td>Immigration ARREST</td><td>ATL Omneon &#x2192; ATL Playback A</td><td class="completed"><img src="img/check.png" />COMPLETED</td><td>00:00:23</td><td>acharlton</td></tr>
<tr><td>03:04:27</td><td><a href="http://bpstools/mediasource_admin/audit.html?selected_mediasource=production____atlanta____mediasource____production_atlanta_mediasource&cnnid=10972276" target="_blank">10972276</td><td>Immigration ARREST</td><td>ATL Omneon &#x2192; ATL Playback B</td><td class="completed"><img src="img/check.png" />COMPLETED</td><td>00:00:23</td><td>acharlton</td></tr>
<tr><td>03:04:10</td><td><a href="http://bpstools/mediasource_admin/audit.html?selected_mediasource=production____atlanta____mediasource____production_atlanta_mediasource&cnnid=10971850" target="_blank">10971850</td><td>Libya/Ethiopians</td><td>ATL Omneon &#x2192; NY Omneon</td><td class="completed"><img src="img/check.png" />COMPLETED</td><td>00:02:12</td><td>mreynard</td></tr>
<tr><td>03:02:18</td><td><a href="http://bpstools/mediasource_admin/audit.html?selected_mediasource=production____atlanta____mediasource____production_atlanta_mediasource&cnnid=07637609" target="_blank">07637609</td><td>DADAAB REFUGEE RELOCATE</td><td>ATL Omneon &#x2192; NY Omneon</td><td class="completed"><img src="img/check.png" />COMPLETED</td><td>00:01:58</td><td>mreynard</td></tr>
<tr><td>03:02:07</td><td><a href="http://bpstools/mediasource_admin/audit.html?selected_mediasource=production____atlanta____mediasource____production_atlanta_mediasource&cnnid=10971829" target="_blank">10971829</td><td>Somalia Nowhere to Go</td><td>ATL Omneon &#x2192; NY Omneon</td><td class="completed"><img src="img/check.png" />COMPLETED</td><td>00:01:45</td><td>mreynard</td></tr>
<tr><td>02:59:56</td><td><a href="http://bpstools/mediasource_admin/audit.html?selected_mediasource=production____atlanta____mediasource____production_atlanta_mediasource&cnnid=10972057" target="_blank">10972057</td><td>WH jumper scene</td><td>ATL Omneon &#x2192; ATL Playback A</td><td class="completed"><img src="img/check.png" />COMPLETED</td><td>00:00:33</td><td>mckinneye</td></tr>
<tr><td>02:59:56</td><td><a href="http://bpstools/mediasource_admin/audit.html?selected_mediasource=production____atlanta____mediasource____production_atlanta_mediasource&cnnid=10972057" target="_blank">10972057</td><td>WH jumper scene</td><td>ATL Omneon &#x2192; ATL Playback B</td><td class="completed"><img src="img/check.png" />COMPLETED</td><td>00:00:33</td><td>mckinneye</td></tr>
<tr><td>02:59:45</td><td><a href="http://bpstools/mediasource_admin/audit.html?selected_mediasource=production____atlanta____mediasource____production_atlanta_mediasource&cnnid=10970562" target="_blank">10970562</td><td>Migrant Rescue Effort</td><td>ATL Omneon &#x2192; NY Omneon</td><td class="completed"><img src="img/check.png" />COMPLETED</td><td>00:01:26</td><td>mreynard</td></tr>
<tr><td>02:58:20</td><td><a href="http://bpstools/mediasource_admin/audit.html?selected_mediasource=production____atlanta____mediasource____production_atlanta_mediasource&cnnid=10972728" target="_blank">10972728</td><td>NS FL MIAMI BRUSH FIRE</td><td>ATL Omneon &#x2192; ATL Playback A</td><td class="completed"><img src="img/check.png" />COMPLETED</td><td>00:00:44</td><td>mckinneye</td></tr>
<tr><td>02:58:20</td><td><a href="http://bpstools/mediasource_admin/audit.html?selected_mediasource=production____atlanta____mediasource____production_atlanta_mediasource&cnnid=10972728" target="_blank">10972728</td><td>NS FL MIAMI BRUSH FIRE</td><td>ATL Omneon &#x2192; ATL Playback B</td><td class="completed"><img src="img/check.png" />COMPLETED</td><td>00:00:44</td><td>mckinneye</td></tr>
<tr><td>02:57:07</td><td><a href="http://bpstools/mediasource_admin/audit.html?selected_mediasource=production____atlanta____mediasource____production_atlanta_mediasource&cnnid=09887746" target="_blank">09887746</td><td>INS:MORSY TRIAL CRT ARR</td><td>ATL Omneon &#x2192; ATL Playback A</td><td class="completed"><img src="img/check.png" />COMPLETED</td><td>00:00:46</td><td>rgigova</td></tr>
<tr><td>02:57:07</td><td><a href="http://bpstools/mediasource_admin/audit.html?selected_mediasource=production____atlanta____mediasource____production_atlanta_mediasource&cnnid=09887746" target="_blank">09887746</td><td>INS:MORSY TRIAL CRT ARR</td><td>ATL Omneon &#x2192; ATL Playback B</td><td class="completed"><img src="img/check.png" />COMPLETED</td><td>00:00:46</td><td>rgigova</td></tr>
<tr><td>02:56:45</td><td><a href="http://bpstools/mediasource_admin/audit.html?selected_mediasource=production____atlanta____mediasource____production_atlanta_mediasource&cnnid=10973628" target="_blank">10973628</td><td>Pakistan:China</td><td>ATL Omneon &#x2192; ATL Playback A</td><td class="completed"><img src="img/check.png" />COMPLETED</td><td>00:00:47</td><td>jseltzer</td></tr>
<tr><td>02:56:45</td><td><a href="http://bpstools/mediasource_admin/audit.html?selected_mediasource=production____atlanta____mediasource____production_atlanta_mediasource&cnnid=10973628" target="_blank">10973628</td><td>Pakistan:China</td><td>ATL Omneon &#x2192; ATL Playback B</td><td class="completed"><img src="img/check.png" />COMPLETED</td><td>00:00:47</td><td>jseltzer</td></tr>
<tr><td>02:56:23</td><td><a href="http://bpstools/mediasource_admin/audit.html?selected_mediasource=production____atlanta____mediasource____production_atlanta_mediasource&cnnid=10973652" target="_blank">10973652</td><td>HENS IOWA BIRD FLU</td><td>ATL Omneon &#x2192; ATL Playback A</td><td class="completed"><img src="img/check.png" />COMPLETED</td><td>00:01:35</td><td>lernert</td></tr>
<tr><td>02:56:23</td><td><a href="http://bpstools/mediasource_admin/audit.html?selected_mediasource=production____atlanta____mediasource____production_atlanta_mediasource&cnnid=10973652" target="_blank">10973652</td><td>HENS IOWA BIRD FLU</td><td>ATL Omneon &#x2192; ATL Playback B</td><td class="completed"><img src="img/check.png" />COMPLETED</td><td>00:01:35</td><td>lernert</td></tr>
<tr><td>02:56:20</td><td><a href="http://bpstools/mediasource_admin/audit.html?selected_mediasource=production____atlanta____mediasource____production_atlanta_mediasource&cnnid=10973652" target="_blank">10973652</td><td>HENS IOWA BIRD FLU</td><td>NY Omneon &#x2192; NY Playback A</td><td class="completed"><img src="img/check.png" />COMPLETED</td><td>00:01:35</td><td>lernert</td></tr>
<tr><td>02:56:18</td><td><a href="http://bpstools/mediasource_admin/audit.html?selected_mediasource=production____atlanta____mediasource____production_atlanta_mediasource&cnnid=10973652" target="_blank">10973652</td><td>HENS IOWA BIRD FLU</td><td>ATL Omneon &#x2192; NY Omneon</td><td class="completed"><img src="img/check.png" />COMPLETED</td><td>00:01:35</td><td>lernert</td></tr>
<tr><td>02:56:11</td><td><a href="http://bpstools/mediasource_admin/audit.html?selected_mediasource=production____atlanta____mediasource____production_atlanta_mediasource&cnnid=10973716" target="_blank">10973716</td><td>STRANDED CRUISE</td><td>ATL Omneon &#x2192; ATL Playback A</td><td class="completed"><img src="img/check.png" />COMPLETED</td><td>00:01:09</td><td>rgigova</td></tr>
<tr><td>02:56:11</td><td><a href="http://bpstools/mediasource_admin/audit.html?selected_mediasource=production____atlanta____mediasource____production_atlanta_mediasource&cnnid=10973716" target="_blank">10973716</td><td>STRANDED CRUISE</td><td>ATL Omneon &#x2192; ATL Playback B</td><td class="completed"><img src="img/check.png" />COMPLETED</td><td>00:01:09</td><td>rgigova</td></tr>
<tr><td>02:55:43</td><td><a href="http://bpstools/mediasource_admin/audit.html?selected_mediasource=production____atlanta____mediasource____production_atlanta_mediasource&cnnid=10968775" target="_blank">10968775</td><td>SMR Bush Walkup</td><td>NY Omneon &#x2192; NY Playback A</td><td class="completed"><img src="img/check.png" />COMPLETED</td><td>00:00:45</td><td>cscretchings</td></tr>
<tr><td>02:55:20</td><td><a href="http://bpstools/mediasource_admin/audit.html?selected_mediasource=production____atlanta____mediasource____production_atlanta_mediasource&cnnid=10973686" target="_blank">10973686</td><td>Asami/immigrants</td><td>ATL Omneon &#x2192; ATL Playback A</td><td class="completed"><img src="img/check.png" />COMPLETED</td><td>00:00:23</td><td>egoldson</td></tr>
<tr><td>02:55:20</td><td><a href="http://bpstools/mediasource_admin/audit.html?selected_mediasource=production____atlanta____mediasource____production_atlanta_mediasource&cnnid=10973686" target="_blank">10973686</td><td>Asami/immigrants</td><td>ATL Omneon &#x2192; ATL Playback B</td><td class="completed"><img src="img/check.png" />COMPLETED</td><td>00:00:23</td><td>egoldson</td></tr>
<tr><td>02:55:07</td><td><a href="http://bpstools/mediasource_admin/audit.html?selected_mediasource=production____atlanta____mediasource____production_atlanta_mediasource&cnnid=10972652" target="_blank">10972652</td><td>Gray arrest</td><td>NY Omneon &#x2192; NY Playback A</td><td class="completed"><img src="img/check.png" />COMPLETED</td><td>00:02:13</td><td>cscretchings</td></tr>
<tr><td>02:54:39</td><td><a href="http://bpstools/mediasource_admin/audit.html?selected_mediasource=production____atlanta____mediasource____production_atlanta_mediasource&cnnid=10322305" target="_blank">10322305</td><td>ND UKRAINE MAGIC WALL</td><td>NY Omneon &#x2192; NY Playback A</td><td class="completed"><img src="img/check.png" />COMPLETED</td><td>00:03:10</td><td>skhan</td></tr>
<tr><td>02:54:01</td><td><a href="http://bpstools/mediasource_admin/audit.html?selected_mediasource=production____atlanta____mediasource____production_atlanta_mediasource&cnnid=10973636" target="_blank">10973636</td><td>Italy/Catania Struggles</td><td>ATL Omneon &#x2192; NY Omneon</td><td class="completed"><img src="img/check.png" />COMPLETED</td><td>00:02:04</td><td>mreynard</td></tr>
<tr><td>02:51:20</td><td><a href="http://bpstools/mediasource_admin/audit.html?selected_mediasource=production____atlanta____mediasource____production_atlanta_mediasource&cnnid=10967476" target="_blank">10967476</td><td>Chris Christie Event</td><td>NY Omneon &#x2192; NY Playback A</td><td class="completed"><img src="img/check.png" />COMPLETED</td><td>00:12:13</td><td>cscretchings</td></tr>
<tr><td>02:51:16</td><td><a href="http://bpstools/mediasource_admin/audit.html?selected_mediasource=production____atlanta____mediasource____production_atlanta_mediasource&cnnid=10970318" target="_blank">10970318</td><td>LEAD CLEAN</td><td>DC Omneon &#x2192; ATL Omneon</td><td>TRANSFERRING: 25%</td><td>01:04:00</td><td>jargumedo</td></tr>
